@url = https://8080-gustavohkol-securitytut-n5atja5qfrw.ws-us118.gitpod.io

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJGQVRFQyBBUEkiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTc0NTk2NDM4Nn0.JfuEAojA10_SvsoI2IijAAJWJNqyrWA3reQ7Qx02Twg

GET {{url}}/categorias
Authorization:  Bearer {{token}}

###
POST {{url}}/categorias
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "nome" : "Ciencias Exatas"
}